# Gitleaks configuration for SelectFileCLI
# This configuration allows specific patterns that are safe for this project

[extend]
# Extend the base configuration
useDefault = true

[allowlist]
# Global allowlist
description = "Global allowlist for SelectFileCLI"
paths = [
    ".gitleaks.toml",
    "gitleaks-report.json",
    "tests/.*",
    "test_.*",
    "snapshot.*"
]

# Allow specific patterns
regexes = [
    "713559\\+Emasoft@users\\.noreply\\.github\\.com",
    "Emasoft",
    "github\\.com/Emasoft",
    "https://github\\.com/Emasoft/.*"
]
