# yamllint configuration
extends: default

rules:
  line-length:
    max: 120
    level: warning
  comments:
    min-spaces-from-content: 1
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
  document-start:
    present: false
  indentation:
    spaces: 2
  brackets:
    max-spaces-inside: 1
