name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
      - name: Build package
        run: |
          uv build
      - name: Check dist contents
        run: |
          ls -la dist/
      - name: Test wheel installation
        run: |
          uv venv test-env
          uv pip install --python test-env/bin/python dist/*.whl
          test-env/bin/python -c "from selectfilecli import select_file; print('Import successful')"
