# pre-commit-sequential.yml - Run pre-commit hooks sequentially using SEP
#
# This workflow runs all pre-commit hooks using the Sequential Execution Pipeline
# to prevent memory exhaustion and process explosions during CI.
#
name: Pre-commit (Sequential)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
    - main
    - develop
  workflow_dispatch:
    inputs:
      all_files:
        description: 'Run on all files (not just changed)'
        required: false
        default: 'false'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sequential-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # Increased for sequential execution
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install 3.12

    - name: Install dependencies
      run: |
        uv sync --locked
        uv pip install pre-commit

    - name: Install additional tools
      run: |
        # Install yamlfmt
        go install github.com/google/yamlfmt/cmd/yamlfmt@latest

        # Install actionlint
        curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
        sudo mv actionlint /usr/local/bin/

    - name: Run pre-commit hooks
      run: |
        # Run pre-commit directly - hooks already handle sequential execution
        if [[ "${{ github.event.inputs.all_files }}" == "true" ]]; then
          pre-commit run --all-files
        else
          pre-commit run --from-ref origin/${{ github.base_ref }} --to-ref HEAD
        fi

    - name: Upload pre-commit log on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: pre-commit-log
        path: ~/.cache/pre-commit/pre-commit.log
        retention-days: 7
