name: Sequential Pre-commit
on:
  pull_request:
  push:
    branches: [main, develop]
# Force sequential workflow execution
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false
env:
  # Same environment as local development
  PRE_COMMIT_MAX_WORKERS: 1
  PYTHONDONTWRITEBYTECODE: 1
  UV_NO_CACHE: 1
  MEMORY_LIMIT_MB: 2048
  TIMEOUT_SECONDS: 600
  TRUFFLEHOG_TIMEOUT: 300
  TRUFFLEHOG_CONCURRENCY: 1
jobs:
  sequential-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # Increased for sequential execution
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
    - name: Create virtual environment
      run: uv venv
    - name: Install dependencies
      run: |
        source .venv/bin/activate
        uv sync --all-extras
        uv pip install pre-commit
    - name: Install local tools
      run: |
        # Install Trufflehog to project bin
        mkdir -p .venv/bin
        curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | \
          sh -s -- -b .venv/bin

        # Install Go (required for yamlfmt)
        # Using the official Go installation method for GitHub Actions
        # Go is pre-installed on GitHub runners, just need to set it up

        # Install yamlfmt
        export PATH=$PATH:/usr/local/go/bin:~/go/bin
        go install github.com/google/yamlfmt/cmd/yamlfmt@latest

        # Install actionlint
        curl -s https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash
        sudo mv actionlint /usr/local/bin/
    - name: Run pre-commit hooks sequentially
      run: |
        source .venv/bin/activate
        # Export same variables as local environment
        export PRE_COMMIT_MAX_WORKERS=1
        export MEMORY_LIMIT_MB=2048
        export TIMEOUT_SECONDS=600

        # Add Go binaries to PATH for yamlfmt
        export PATH=$PATH:/usr/local/go/bin:~/go/bin

        # Make wrapper scripts executable
        chmod +x .pre-commit-wrappers/*.sh || true

        # Run all hooks
        pre-commit run --all-files --show-diff-on-failure
    - name: Memory usage report
      if: always()
      run: |-
        echo "Final memory usage:"
        free -h || true
