# sync.yml - Update dependencies to versions specified in configuration files
#
# This workflow synchronizes dependencies with pyproject.toml and updates
# the lock file when configuration changes.
#
name: Sync Dependencies

on:
  workflow_call:
  workflow_dispatch:
  schedule:
  # Run weekly on Monday at 3 AM UTC
  - cron: '0 3 * * 1'
  push:
    paths:
    - 'pyproject.toml'
    - 'requirements*.txt'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install 3.12

    - name: Check current lock status
      run: |
        # Check if lock file is out of date
        if ./scripts/sep_queue.sh --timeout 600 -- uv lock --check; then
          echo "Lock file is up to date"
          echo "NEEDS_UPDATE=false" >> $GITHUB_ENV
        else
          echo "Lock file needs updating"
          echo "NEEDS_UPDATE=true" >> $GITHUB_ENV
        fi

    - name: Update lock file
      if: env.NEEDS_UPDATE == 'true'
      run: |
        # Update the lock file with latest compatible versions
        ./scripts/sep_queue.sh --timeout 1800 -- uv lock

    - name: Sync dependencies
      run: |
        # Sync to ensure environment matches lock file
        ./scripts/sep_queue.sh --timeout 1800 -- uv sync --locked

    - name: Update development dependencies
      run: |
        # Also update dev and optional dependencies
        ./scripts/sep_queue.sh --timeout 600 -- uv sync --locked --all-extras

    - name: Run dependency check
      run: |
        # Verify all dependencies are properly declared
        ./scripts/sep_queue.sh --timeout 600 -- uv run deptry .

    - name: Run security audit
      run: |
        # Check for known vulnerabilities
        ./scripts/sep_queue.sh --timeout 600 -- uv run pip-audit || true

    - name: Generate dependency report
      run: |
        # Create a report of all dependencies
        echo "# Dependency Report" > dependency-report.md
        echo "" >> dependency-report.md
        echo "Generated on: $(date)" >> dependency-report.md
        echo "" >> dependency-report.md
        echo "## Direct Dependencies" >> dependency-report.md
        echo '```' >> dependency-report.md
        uv pip list --format freeze | grep -E '^(textual|rich|click)' >> dependency-report.md
        echo '```' >> dependency-report.md
        echo "" >> dependency-report.md
        echo "## All Dependencies" >> dependency-report.md
        echo '```' >> dependency-report.md
        uv pip list >> dependency-report.md
        echo '```' >> dependency-report.md

    - name: Check for changes
      id: git-check
      run: |
        if [[ -n $(git diff --name-only uv.lock) ]]; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Pull Request
      if: steps.git-check.outputs.changes == 'true'
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: update dependencies'
        body: |
          ## Dependency Update

          This PR updates the `uv.lock` file to match the current `pyproject.toml` specifications.

          ### Changes
          - Updated lock file with latest compatible versions
          - All tests have been run with the updated dependencies

          Please review the dependency changes before merging.
        branch: deps/update-lock-file
        delete-branch: true
