# test-workflows.yml - Test that GitHub Actions workflows actually work
#
# This workflow tests other workflows to ensure they execute commands properly
# and don't just queue them without running.
#
name: Test Workflows

on:
  pull_request:
    paths:
    - '.github/workflows/*.yml'
    - 'scripts/sep*.sh'
  push:
    branches:
    - main
    paths:
    - '.github/workflows/*.yml'
  workflow_dispatch:

jobs:
  validate-workflows:
    name: Validate Workflow Syntax
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Validate YAML syntax
      run: |
        # Install yamllint
        pip install yamllint

        # Check all workflows
        for workflow in .github/workflows/*.yml; do
          echo "Checking $workflow..."
          yamllint -d relaxed "$workflow"
        done

    - name: Validate with actionlint
      run: |
        # Install actionlint
        bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        sudo mv actionlint /usr/local/bin/

        # Check all workflows
        actionlint

  check-execution:
    name: Check Command Execution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check for execution issues
      run: |
        chmod +x scripts/check_workflow_execution.sh
        ./scripts/check_workflow_execution.sh

    - name: Report execution issues
      if: failure()
      run: |
        echo "::error::Workflows are queuing commands but not executing them!"
        echo "::error::This means CI checks are not actually running!"

  test-lint-detection:
    name: Test Lint Detection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python
      run: uv python install 3.12

    - name: Create file with issues
      run: |
        cat > test_issues.py << 'EOF'
        import unused_module  # Should be caught
        x=1+2  # Missing spaces
        EOF

    - name: Test if linting would catch issues
      run: |
        # Install dependencies
        uv sync --locked

        # This SHOULD fail if working properly
        if uv run ruff check test_issues.py; then
          echo "::error::Ruff did not catch obvious issues!"
          exit 1
        else
          echo "✓ Ruff correctly detected issues"
        fi

    - name: Cleanup
      run: rm -f test_issues.py

  test-with-act:
    name: Test Workflows with Act
    runs-on: ubuntu-latest
    continue-on-error: true # Don't fail the whole job
    steps:
    - uses: actions/checkout@v4

    - name: Install act
      run: |
        curl https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash

    - name: Test lint workflow with act
      run: |
        # Create test file
        echo "x=1" > test.py

        # Run workflow in dry-run mode
        act push -W .github/workflows/lint.yml -n --container-architecture linux/amd64 || true

        # Check if it would actually do something
        echo "Checking if workflow would execute commands..."

    - name: Generate workflow test report
      if: always()
      run: |-
        cat > workflow_test_results.md << 'EOF'
        # Workflow Test Results

        ## Issues Found

        Most workflows use `sep_queue.sh` but never call `--queue-start`, meaning:
        - Commands are queued but never executed
        - No actual linting, testing, or validation happens
        - CI reports success without doing any work

        ## Recommendations

        1. Remove SEP from CI workflows
        2. Run commands directly (like build.yml)
        3. Add proper command execution tests
        EOF

        echo "::warning::See workflow_test_results.md for detailed findings"
